# Generated by Django 3.2.4 on 2021-07-18 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='dat_posted',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
