# Generated by Django 3.2.4 on 2021-07-18 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_rename_user_projects_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
