# Generated by Django 3.2.4 on 2021-07-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_alter_projects_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='image',
        ),
    ]
